name: Bearer

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bearer SAST
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: sarif                     # choose output format
          # Include all severities in the report:
          severity: critical,high,medium,low,warning
          # Fail pipeline only on high/critical:
          args: --fail-on-severity critical,high
