name: Bearer

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bearer SAST
        id: report
        uses: bearer/bearer-action@v2
